### ISSUE TITLE
程序启动后默认设置连接后无法使用绝对坐标模式，随意拖动一下程序窗体大小后绝对模式才能正常使用

### ISSUE THREAD

**Issue by EarthTuzki** [wevsty/KVM-over-USB#1]
系统 ：Win10 22H2 64
软件：Python 3.12.7，使用poetry install依赖库后编译（使用release里编译好的版本也是同样情况）
主控电脑：4k分辨率
被控电脑：1080p分辨率

程序启动后，默认设置连接成功后，鼠标无法移动（可左右击），无法使用绝对坐标模式移动鼠标，只能使用相对模式很不方便，发现随意拖动一下程序窗体大小后绝对模式即可恢复正常使用，以下是当时python后台报错：
Error calling Python override of QMainWindow::mouseMoveEvent(): Traceback (most recent call last):
  File "D:\KVM\source\KVM-over-USB-20241105\client\main.py", line 1729, in mouseMoveEvent
    self.update_mouse_position_buffer(x, y)
  File "D:\KVM\source\KVM-over-USB-20241105\client\main.py", line 1633, in update_mouse_position_buffer
    self.update_mouse_position_buffer_with_absolute_mode(x, y)
  File "D:\KVM\source\KVM-over-USB-20241105\client\main.py", line 1593, in update_mouse_position_buffer_with_absolute_mode
    x_hid = (x - x_diff / 2 - x_pos) / (width - x_diff)
                 ^^^^^^
UnboundLocalError: cannot access local variable 'x_diff' where it is not associated with a value

**Comment by wevsty** [comment]
从报错信息上看是 x_diff 这个变量无法访问。
应该是在配置文件 keep_aspect_ratio 选项为 false 的时候会发生这个问题，[v2024.11.08](https://github.com/wevsty/KVM-over-USB/releases/tag/v2024.11.08) 这个版本中我已经修复。

试试看新版本，应该能解决，如果还有问题欢迎继续反馈。

**Comment by EarthTuzki** [comment]
> 从报错信息上看是 x_diff 这个变量无法访问。 应该是在配置文件 keep_aspect_ratio 选项为 false 的时候会发生这个问题，默认配置下 keep_aspect_ratio 为 true 应该不会出现该问题。 新版本：[v2024.11.08](https://github.com/wevsty/KVM-over-USB/releases/tag/v2024.11.08)
> 
> 试试看新版本，应该能解决，如果还有问题欢迎继续反馈。

大佬，新版已经没问题了，非常感谢！看着从原版的打字难打、鼠标点击有问题、鼠标不好拖动等等各种各样的问题被一一解决，到现在功能越来越完善，希望这么好的项目能让更多人看到。
